FROM debian:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    git \
    sudo

RUN useradd -m -s /bin/bash linuxbrew && \
    echo "linuxbrew ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    su - linuxbrew -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" </dev/null

ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

ARG BIN
COPY $BIN /usr/local/bin/stamp
COPY test/integration/debian.sh /test.sh
CMD ["/test.sh"]
