version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unused
  settings:
    govet:
      enable-all: true
      disable:
        - shadow

formatters:
  enable:
    - gofmt
    - goimports
