sonar.projectKey=rossijonas_stamp
sonar.organization=rossijonas

sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/docs/**,**/bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
